TestRuby/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('',RedirectView.as_view(url ='',permanent = True)),
]

catalog/urls.py
from django.views.decorators.csrf import csrf_exempt

from . import views
from django.urls import path
app_name = 'catalog'
urlpatterns = [
    path('', csrf_exempt(views.ProjectListView.as_view()), name='project'),
]

catalog/models.py
from django.db import models


# Create your models here.

class Project(models.Model):
    name = models.CharField(max_length=1000, help_text="Enter a  project")

    def __str__(self): return self.name


class Record(models.Model):
    text = models.CharField(max_length=1000, help_text="Enter a task")
    project = models.ForeignKey('Project', on_delete=models.SET_NULL, null=True)
    status = models.BooleanField(default=False)
    def __str__(self): return self.text

catalog/forms.py
from django import forms

class RecordForm(forms.Form):
    post = forms.CharField()

catalog/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render
from django.views import generic
from django.views.decorators.csrf import csrf_exempt

from .models import Project, Record
# Create your views here.
from .forms import RecordForm
from django.views.generic.edit import CreateView


class ProjectListView(generic.ListView, ):
    model = Project

    def get_context_data(self, **kwargs):
        context = super(ProjectListView, self).get_context_data(**kwargs)
        context.update({
            'project_list': Project.objects.all(),
            'record_list': Record.objects.all(),
        })
        return context

    def post(self, request):
        project = [i.name for i in Project.objects.all()]
        record = [i.text for i in Record.objects.all()]
        str_addrecord = []
        str_deleterecord = []
        str_record_add = []
        str_checkbox = []
        str_deleteproject=[]
        for p in project:
            add_str = 'record_field_' + str(p)
            del_str = 'deleteproject_'+str(p)
            str_record_add.append(add_str)
            str_deleteproject.append(del_str)

        for p in project:
            add_str = 'addrecord_' + str(p) + '_'
            checkbox_str = 'checkbox_'+ str(p) + '_'
            delete_str = 'deleterecord_' + str(p) + '_'
            for r in record:
                add_str += str(r)
                checkbox_str += str(r)
                delete_str += str(r)
                str_deleterecord.append(delete_str)
                str_addrecord.append(add_str)
                str_checkbox.append(checkbox_str)
                checkbox_str = 'checkbox_' + str(p) + '_'
                add_str = 'addrecord_' + str(p) + '_'
                delete_str = 'deleterecord_' + str(p) + '_'
        str_list = str_addrecord + str_deleterecord
        if request.method == "POST":
            for item in str_list:
                if item in request.POST:
                    if "addrecord" in item:
                        print("add")
                    else:
                        print("del")
                        for project in Project.objects.all():
                            if item.split('_')[1] == project.name:
                                print(project.name)
                                for r in Record.objects.all():
                                    if item.split('_')[2] == r.text:

                                        Record.objects.filter(project__name=project, text = r.text).delete()
                                        break
                                break

            for item in str_record_add:
                if item in request.POST:
                    data = dict(request.POST)

                    check = True

                    for project in Project.objects.all():
                        if str(list(data.keys())[1]).split('_')[2] == project.name:
                            for record in Record.objects.filter(project=project):
                                if list(data.values())[1][0] == record.text:
                                    check = False
                            if check:
                                if list(data.values())[1][0] != '':
                                    Record.objects.create(text=list(data.values())[1][0], project=project)
                            break

            for item in str_checkbox:
                print(request.POST)
                if item in request.POST:
                    print(item)
                    for project in Project.objects.all():
                        if item.split('_')[1] == project.name:
                            print(project.name)
                            print(request.POST[item])
                            for r in Record.objects.all():
                                if item.split('_')[2] == r.text:
                                    if r.status == 0:
                                        print("1")
                                        Record.objects.filter(project__name=project, text=r.text).update(status = 1)
                                        break
            if 'add_list' in request.POST:
                data = dict(request.POST)
                if list(data.values())[1][0] != '':
                    Project.objects.create(name=list(data.values())[1][0])

            for item in str_deleteproject:

                if item in request.POST:
                    print(item)
                    for project in Project.objects.all():
                        if item.split('_')[1] == project.name:
                            Record.objects.filter(project=project).delete()
                            Project.objects.filter(name=project.name).delete()

                            break
        context = {
            'project_list': Project.objects.all(),
            'record_list': Record.objects.all()}
        return render(request, "catalog/project_list.html", context)

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body style="height: 100%">
    {% block content %}
    {% endblock %}
    <div class="row d-flex justify-content-center" style="margin-top:50px; " >
        <div class="card" style="width: 750px;display: none" id="create_div">
            <div class="card-header " style="background-color: beige" >
                                <div class="row" >

                                    <div class="col">

                                            <form method="post" action="{% url 'catalog:project' %}">
                                                {% csrf_token %}
                                                 <div class="input-group" >
                                                        <input type="text" class="form-control" name="add_list" placeholder="Start typing here to create a list..." aria-describedby="basic-addon2">
                                                        <div class="input-group-append">
                                                            <button class="btn btn-success" type="submit" id="add_list">Add List</button>
                                                          </div>

                                                  </div>
                                            </form>
                                    </div>
                            </div>
            </div>
        </div>
    </div>
    <div class="container" style="text-align: center; padding-top: 30px">
         <button class="btn" id="create_list" style="background-color: blue; color: white"><i class="fa fa-plus" aria-hidden="true"></i>  Add TODO List</button>
    </div>

    <script>
        $(document).ready(function () {
            $("#create_list").click(function () {
                $("#create_div").show();
            })
            $("#add_list").click(function () {
                $("#create_div").hide();
            })
        });
    </script>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/create_record.html
{% extends "project_list.html" %}

{% block content %}

{% endblock %}

catalog/templates/catalog/project_list.html
{% extends "base_generic.html" %}

{% block content %}
    {% if project_list %}

        {% for project in project_list %}

            <div class="row d-flex justify-content-center" style="margin-top:50px;">
                <div class="card"  style="width: 750px">
                    <div class="card-header " style="background-color: blue" >
                        <div class="row">
                            <div class="col-11 text-white " style="font-size: 25px;">
                                 <a ><i class="fa fa-calendar" aria-hidden="true"></i>  {{project.name}}</a>
                            </div>
                                <!--<div class="col-1">
                                    <button  class="btn btn-success" id="btn1" type="button" style="display: none;"><i class="fa fa-pencil" aria-hidden="true"></i></button>
                                </div>-->
                                <div class="col-1 ">
                                    <form method="post" action="{% url 'catalog:project' %}">
                                        {% csrf_token %}
                                        <button  class="btn btn-danger" id="btn2" name="deleteproject_{{ project.name }}" type="submit" style="display: none;"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                                    </form>
                                </div>
                            </div>

                            </div>

                    <div class="card-header " style="background-color: beige" >
                            <div class="row" >
                                <div class="col-1">
                                    <i class="fa fa-plus" aria-hidden="true" style="font-size:35px;color:green"></i>
                                </div>
                                <div class="col">

                                        <form method="post" action="{% url 'catalog:project' %}">
                                            {% csrf_token %}
                                             <div class="input-group" >
                                                    <input type="text" class="form-control" name="record_field_{{ project.name }}" placeholder="Start typng here to create a task..." aria-describedby="basic-addon2">
                                                    <div class="input-group-append">
                                                        <button class="btn btn-success" type="submit">Add Task</button>
                                                      </div>

                                              </div>
                                        </form>
                                </div>
                        </div>
                    </div>

                            {% for record in record_list %}
                                {% if project == record.project %}
                                    <div class="card-header" id="record" style="background-color: white">
                                        <div class="row">
                                            <div class="col-1 text-center" style="" >
                                            <form method="POST" action="{% url 'catalog:project' %}" id="form_check">
                                                    {% csrf_token %}
                                                    <input type="checkbox" class="form-check-input" onChange="this.form.submit()" name="checkbox_{{ project.name }}_{{ record.text }}" {% if record.status == 1 %}checked="checked"{% endif %}>
                                            </form>
                                            </div>
                                            <div class="col-10 border-left border-right">{{ record }}</div>
                                            <div class="col-1">
                                                <form method="post" action="{% url 'catalog:project' %}">
                                                    {% csrf_token %}
                                                    <div class="btn-group" role="group">
                                                            <!--<button  class="btn btn-success" id="btn1_record" name="addrecord_{{ project.name }}_{{ record.text }}" type="submit" style="display: none;"><i class="fa fa-pencil" aria-hidden="true"></i></button>-->
                                                            <button  class="btn btn-danger" id="btn2_record" name="deleterecord_{{ project.name }}_{{ record.text }}" type="submit" style="display: none;"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                                                        </div>
                                                </form>
                                            </div>


                                        </div>

                                    </div>
                                {% endif %}
                            {% endfor %}




                </div>
            </div>
            <script>

                $(document).ready(function () {
                    $(document).on('mouseenter', '.card', function () {
                        $(this).find("#btn1").show();
                        $(this).find("#btn2").show();
                    }).on('mouseleave', '.card', function () {
                        $(this).find("#btn1").hide();
                        $(this).find("#btn2").hide();
                    });


                });
                $(document).ready(function () {
                    $(document).on('mouseenter', '#record', function () {
                        $(this).find("#btn1_record").show();
                        $(this).find("#btn2_record").show();
                        $(this).find("#btn_arrow1").show();
                        $(this).find("#btn_arrow2").show();
                        $(this).css('background-color', 'gainsboro');
                    }).on('mouseleave', '#record', function () {
                        $(this).find("#btn1_record").hide();
                        $(this).find("#btn2_record").hide();
                        $(this).find("#btn_arrow1").hide();
                        $(this).find("#btn_arrow2").hide();
                        $(this).css('background-color', 'white');
                    });
                });
            </script>

        {% endfor %}
    {% endif %}
{% endblock %}